core/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as users_views
from maps import views as maps_views

urlpatterns = [
    path('', maps_views.render_map, name='map'),
    path('admin/', admin.site.urls),
    path('home/', users_views.home, name='users-home'),
    path('profile/', users_views.profile, name='profile'),
    path('register/', users_views.register, name='register'),
    path('login/',
         auth_views.LoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('map/', maps_views.render_map, name='map'),
    path('about/', maps_views.about_page, name='about'),
    path('map/<str:start>/<str:destination>/', maps_views.fetch_route_with_traffic, name='fetch-route-with-traffic'),
    path('map/weather/<str:lat>/<str:long>/', maps_views.fetch_weather, name='fetch-weather'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    phone = models.CharField(max_length=14, blank=False, null=False, unique=True, db_index=False)
    country_code = models.CharField(max_length=5, blank=False, null=False, db_index=False, default="IN")

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
import re

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']
        help_texts = {
            'username': 'Required. 15 characters or fewer. Letters, digits and @/./+/-/_ only.',
        }

    def clean(self):
        # data from the form is fetched using super function
        super(UserUpdateForm, self).clean()

        # extract the username and text field from the data
        username = self.cleaned_data.get('username')

        # conditions to be met for the username length
        if len(username) > 15:
            self._errors['username'] = self.error_class([
                'Maximum 15 characters allowed.'])

        # return any errors if found
        return self.cleaned_data


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'country_code', 'phone']


class ProfilePhoneNumberForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['country_code', 'phone']

    def clean(self):
        # data from the form is fetched using super function
        super(ProfilePhoneNumberForm, self).clean()

        # extract the username and text field from the data
        phone = self.cleaned_data.get('phone')
        if not re.match(r'\d{4,10}', phone):
            self._errors['phone'] = self.error_class([
                'Invalid phone number.'])
        # return any errors if found
        return self.cleaned_data

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, ProfilePhoneNumberForm
from django.contrib import messages

from .models import Profile


@login_required
def home(request):
    return redirect('map')


def register(request):
    if request.user.is_authenticated:
        return redirect('users-home')
    context = {}
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        phone_number_form = ProfilePhoneNumberForm(request.POST)
        if form.is_valid() and phone_number_form.is_valid():
            instance = form.save()
            Profile.objects.create(user=instance, phone=request.POST.get('phone'), country_code=request.POST.get('country_code'))
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}')
            return redirect('login')
    else:
        form = UserRegisterForm()
        phone_number_form = ProfilePhoneNumberForm()
    context['form'] = form
    context['phone_number_form'] = phone_number_form
    context['title'] = 'Register'
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    if request.method=="POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account has been updated')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

users/templates/users/base.html
<!doctype html>
<html lang="ar">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% if title %}
            Website - {{ title }}
        {% else %}
            Website Name
        {% endif %}
    </title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    {% block styleblock %}
    {% endblock styleblock %}
    <style>
        .form-group:not(:first-of-type) {
            margin-top: 0.8rem;
        }

        .dot {
            height: 30px;
            width: 30px;
            border-radius: 50%;
            display: inline-block;
            margin-right: 6px;
        }

        .aligned {
            display: flex;
            align-items: center;
        }
    </style>
</head>
<body style="background: #e3eaff">
<nav class="navbar navbar-expand-lg bg-white py-3">
    <div class="container-fluid">
        <div class="aligned">
            <span class="dot bg-warning"></span>

            <a class="navbar-brand text-warning font-weight-bold text-uppercase" href="#">My Maps</a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'users-home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                </li>
                {% if not request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'map' %}">Map</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container my-md-4 py-md-2 rounded">
    {% if messages %}
        <div class="alert alert-info my-3">
            {% for message in messages %}
                <div>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row mt-2">
        <div class="offset-md-1 offset-md-3 col-md-6 rounded bg-white">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="col-12 rounded mt-2">
            {% block map_content %}
            {% endblock map_content %}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% include 'users/chatbot.html' %}

{% block jsblock %}
{% endblock jsblock %}
</body>
</html>

users/templates/users/chatbot.html
<script type="text/javascript">
    (function(d, m){
        var kommunicateSettings =
            {"appId":"12d01f136d338981831662c04ffb12493","popupWidget":true,"automaticChatOpenOnNavigation":true};
        var s = document.createElement("script"); s.type = "text/javascript"; s.async = true;
        s.src = "https://widget.kommunicate.io/v2/kommunicate.app";
        var h = document.getElementsByTagName("head")[0]; h.appendChild(s);
        window.kommunicate = m; m._globals = kommunicateSettings;
    })(document, window.kommunicate || {});
/* NOTE : Use web server to view HTML files as real-time update will not work if you directly open the HTML file in the browser. */
</script>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    Welcome, {{ request.user }}
{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% if form %}
        <div class="px-4 py-3">
            <form method="post" class="card border-0 mx-lg-5">
                {% csrf_token %}
                <fieldset class="form-group  text-center">
                    <legend class="border-bottom mb-3">
                        <h3>Sign In</h3>
                    </legend>
                </fieldset>
                {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-primary btn-block mt-3 border-0" style="background: #bca3fb">
                    Login
                </button>
                <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'register' %}"
                                                                                  class="link-primary text-decoration-none">Register</a>
                </p>
            </form>
        </div>
    {% endif %}
{% endblock content %}

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <p>You have been logged out!</p>
{% endblock content %}

users/templates/users/phonenumber_form.html
<div class="form-group">
<input type="text" name="country_code" value="IN" maxlength="5" required="" id="id_country_code" hidden="true">
<input id="phone" type="tel" required name="phone" class="textinput textInput form-control">
</div>

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-4">
            <img class="rounded-circle" src="{{ request.user.profile.image.url }}" alt="" style="width:100%">
        </div>
        <div class="col-6 border-start">
            <div>
                <h2 class="text-uppercase">{{ request.user.username }}</h2>
            </div>
            {% if request.user.email %}
                <div>
                    Email: {{ request.user.email }}
                </div>
            {% else %}
                <div>
                    Email: N/A
                </div>
            {% endif %}
        </div>
    </div>
    <form method="post" enctype="multipart/form-data" class="mt-3">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">
                Profile
            </legend>
        </fieldset>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
        <button type="submit" class="btn btn-primary btn-block mt-3 border-0" style="background: #bca3fb">Update
        </button>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block styleblock %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.9/css/intlTelInput.css" rel="stylesheet"
          media="screen">
{% endblock styleblock %}
{% block content %}
    {% if form %}
        <div class="px-4 py-3">
            <form method="post" class="card border-0 mx-lg-5">
                {% csrf_token %}
                <fieldset class="form-group text-center">
                    <legend class="border-bottom mb-3">
                        <h4>Join Today</h4>
                    </legend>
                </fieldset>
                {{ form|crispy }}
                {% include 'users/phonenumber_form.html' %}
                <button type="submit" class="btn btn-primary btn-block mt-3 border-0" style="background: #bca3fb">
                    Register
                </button>
                <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account? <a href="{% url 'login' %}"
                                                                                    class="text-decoration-none link-primary">Login</a>
                </p>
            </form>
        </div>
    {% endif %}
{% endblock content %}

{% block jsblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.9/js/intlTelInput.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.9/js/intlTelInput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.9/js/utils.js"></script>

    <script>
        var telInput = $("#phone"),
            errorMsg = $("#error-msg"),
            validMsg = $("#valid-msg");

        // initialise plugin
        telInput.intlTelInput({

            allowExtensions: true,
            formatOnDisplay: true,
            autoFormat: true,
            autoHideDialCode: true,
            autoPlaceholder: true,
            defaultCountry: "auto",
            ipinfoToken: "yolo",

            nationalMode: false,
            numberType: "MOBILE",
            //onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'],
            preferredCountries: ['sa', 'ae', 'qa', 'om', 'bh', 'kw', 'ma'],
            preventInvalidNumbers: true,
            separateDialCode: true,
            initialCountry: "auto",
            geoIpLookup: function (callback) {
                $.get("http://ipinfo.io", function () {
                }, "jsonp").always(function (resp) {
                    var countryCode = (resp && resp.country) ? resp.country : "";
                    {#callback(countryCode);#}
                    callback('US');
                });
            },
            utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/11.0.9/js/utils.js"
        });

        var reset = function () {
            telInput.removeClass("error");
            errorMsg.addClass("hide");
            validMsg.addClass("hide");
        };

        // on blur: validate
        telInput.blur(function () {
            reset();
            if ($.trim(telInput.val())) {
                if (telInput.intlTelInput("isValidNumber")) {
                    validMsg.removeClass("hide");
                } else {
                    telInput.addClass("error");
                    errorMsg.removeClass("hide");
                }
            }
        });

        // on keyup / change flag: reset
        telInput.on("keyup change", reset);

        $("#phone").on('input', function(){
            const country_code = $(".selected-dial-code")[0]
            const input_ele = $("#id_country_code")[0]
            input_ele.value = country_code.innerHTML
        })

        $("#hint_id_username").html("Required. 15 characters or fewer. Letters, digits and @/./+/-/_ only.")
        $("#id_username").attr('maxlength','15');
    </script>
{% endblock jsblock %}